"use client";

import { useLanguage } from "@/contexts/language-context";

const content = {
  en: {
    title: "Terms of Service",
    lastUpdated: "Last updated: May 31, 2026",
    sections: [
      {
        heading: "1. Acceptance of Terms",
        body: 'By accessing or using the BotForge AI platform ("Service"), you agree to be bound by these Terms of Service ("Terms"). If you do not agree to these Terms, do not use the Service. We may update these Terms at any time; continued use after changes constitutes acceptance.',
      },
      {
        heading: "2. Description of Service",
        body: "BotForge AI is a cloud-based platform that allows users to create, configure, and deploy AI-powered chatbots for lead generation and customer communication via website widgets and Telegram. The Service includes bot creation, knowledge base management, analytics, and channel integrations.",
      },
      {
        heading: "3. Account Registration",
        body: "You must provide accurate, complete information when creating an account. You are responsible for maintaining the security of your account credentials and for all activity under your account. You must be at least 18 years old or the age of legal majority in your jurisdiction to use the Service.",
      },
      {
        heading: "4. Acceptable Use",
        body: "You agree not to: (a) use the Service for any unlawful purpose or in violation of any applicable laws; (b) transmit spam, malware, or harmful content through your bots; (c) impersonate any person or entity; (d) attempt to gain unauthorized access to the Service or its infrastructure; (e) use the Service to collect personal data without proper consent; (f) resell or redistribute the Service without written permission.",
      },
      {
        heading: "5. Your Content & Data",
        body: "You retain ownership of all content you upload to the Service (documents, knowledge base files, bot configurations). By uploading content, you grant BotForge AI a limited license to process, store, and serve that content solely for the purpose of operating the Service. You are responsible for ensuring you have the right to use any content you upload.",
      },
      {
        heading: "6. AI-Generated Responses",
        body: "Chatbot responses are generated by artificial intelligence models and may not always be accurate, complete, or appropriate. BotForge AI does not guarantee the accuracy of AI-generated content. You are responsible for reviewing and configuring your bot's behavior, knowledge base, and tone to suit your use case. BotForge AI is not liable for any decisions made based on AI-generated responses.",
      },
      {
        heading: "7. Pricing & Payments",
        body: "Free plans are available with usage limitations. Paid plans are billed monthly via Stripe. All fees are non-refundable except as required by applicable law. We reserve the right to change pricing with 30 days' notice. If payment fails, your account may be downgraded to the free tier after a grace period.",
      },
      {
        heading: "8. Service Availability",
        body: "We strive for high availability but do not guarantee uninterrupted access. The Service may be temporarily unavailable due to maintenance, updates, or circumstances beyond our control. We will make reasonable efforts to notify users of planned downtime.",
      },
      {
        heading: "9. Limitation of Liability",
        body: "To the maximum extent permitted by law, BotForge AI and its affiliates shall not be liable for any indirect, incidental, special, consequential, or punitive damages, or any loss of profits, revenue, data, or business opportunities arising from your use of the Service. Our total liability shall not exceed the amount you paid for the Service in the 12 months preceding the claim.",
      },
      {
        heading: "10. Termination",
        body: "You may delete your account at any time. We may suspend or terminate your access if you violate these Terms or engage in activity that harms the Service or other users. Upon termination, your data will be deleted within 30 days unless retention is required by law.",
      },
      {
        heading: "11. Intellectual Property",
        body: "The Service, including its design, code, branding, and documentation, is the intellectual property of BotForge AI. These Terms do not grant you any rights to our trademarks, logos, or other proprietary materials. Feedback you provide may be used to improve the Service without obligation to you.",
      },
      {
        heading: "12. Governing Law",
        body: "These Terms are governed by and construed in accordance with applicable international commercial law. Any disputes shall be resolved through good-faith negotiation first, then through binding arbitration if necessary.",
      },
      {
        heading: "13. Contact",
        body: "For questions about these Terms, contact us at support@botforge.ai.",
      },
    ],
  },
  uz: {
    title: "Xizmat ko'rsatish shartlari",
    lastUpdated: "Oxirgi yangilanish: 2026-yil 31-may",
    sections: [
      {
        heading: "1. Shartlarni qabul qilish",
        body: 'BotForge AI platformasiga ("Xizmat") kirish yoki undan foydalanish orqali siz ushbu Xizmat ko\'rsatish shartlariga ("Shartlar") rozilik bildirasiz. Agar siz ushbu Shartlarga rozi bo\'lmasangiz, Xizmatdan foydalanmang. Biz ushbu Shartlarni istalgan vaqtda yangilashimiz mumkin; o\'zgarishlardan keyin foydalanishni davom ettirish qabul qilish hisoblanadi.',
      },
      {
        heading: "2. Xizmat tavsifi",
        body: "BotForge AI — foydalanuvchilarga veb-sayt vidjeti va Telegram orqali lid generatsiyasi va mijozlar bilan muloqot uchun sun'iy intellektga asoslangan chatbotlarni yaratish, sozlash va joylashtirish imkonini beruvchi bulutli platforma. Xizmatga bot yaratish, bilimlar bazasini boshqarish, tahlillar va kanal integratsiyalari kiradi.",
      },
      {
        heading: "3. Hisob ro'yxatdan o'tish",
        body: "Hisob yaratishda aniq va to'liq ma'lumotlarni taqdim etishingiz kerak. Hisob ma'lumotlaringiz xavfsizligini saqlash va hisobingizdagi barcha faoliyat uchun siz javobgarsiz. Xizmatdan foydalanish uchun kamida 18 yoshda yoki yurisdiktsiyangizda qonuniy voyaga yetgan bo'lishingiz kerak.",
      },
      {
        heading: "4. Foydalanish qoidalari",
        body: "Siz quyidagilarni qilmaslikka rozilik bildirasiz: (a) Xizmatdan noqonuniy maqsadlarda foydalanish; (b) botlaringiz orqali spam, zararli dastur yoki zararli kontent tarqatish; (c) boshqa shaxs yoki tashkilot sifatida ko'rinish; (d) Xizmat yoki uning infratuzilmasiga ruxsatsiz kirish; (e) tegishli rozilik olmagan holda shaxsiy ma'lumotlarni yig'ish; (f) yozma ruxsatsiz Xizmatni qayta sotish.",
      },
      {
        heading: "5. Kontentingiz va ma'lumotlaringiz",
        body: "Siz Xizmatga yuklagan barcha kontent (hujjatlar, bilimlar bazasi fayllari, bot sozlamalari) ustidan egalik huquqini saqlab qolasiz. Kontent yuklash orqali siz BotForge AI ga faqat Xizmatni ishlatish maqsadida kontentni qayta ishlash, saqlash va taqdim etish uchun cheklangan litsenziya berasiz.",
      },
      {
        heading: "6. AI tomonidan yaratilgan javoblar",
        body: "Chatbot javoblari sun'iy intellekt modellari tomonidan yaratiladi va har doim aniq, to'liq yoki mos bo'lmasligi mumkin. BotForge AI yaratilgan kontent aniqligini kafolatlamaydi. Botingiz xatti-harakatlarini, bilimlar bazasini va ohangini sozlash sizning javobgarligingiz. BotForge AI AI javoblariga asoslangan qarorlar uchun javobgar emas.",
      },
      {
        heading: "7. Narxlar va to'lovlar",
        body: "Foydalanish cheklovlari bilan bepul rejalar mavjud. Pullik rejalar Stripe orqali oylik hisoblanadi. Barcha to'lovlar qaytarilmaydi, qonun talab qilgan holatlar bundan mustasno. Biz 30 kun oldin xabardor qilib narxlarni o'zgartirishga haqimiz bor. To'lov muvaffaqiyatsiz bo'lsa, hisobingiz bepul rejaga tushirilishi mumkin.",
      },
      {
        heading: "8. Xizmat mavjudligi",
        body: "Biz yuqori mavjudlikka intilamiz, lekin uzluksiz kirishni kafolatlamaymiz. Xizmat texnik xizmat ko'rsatish, yangilanishlar yoki boshqarib bo'lmaydigan holatlar tufayli vaqtinchalik ishlamasligi mumkin. Rejalashtirilgan to'xtash vaqtlari haqida foydalanuvchilarga xabar berishga harakat qilamiz.",
      },
      {
        heading: "9. Javobgarlik cheklovi",
        body: "Qonun ruxsat etgan eng katta darajada BotForge AI va uning hamkorlari Xizmatdan foydalanishingiz natijasida yuzaga kelgan bilvosita, tasodifiy, maxsus, oqibatli yoki jazo zarar uchun javobgar bo'lmaydi. Bizning umumiy javobgarligimiz da'vo oldidagi 12 oy davomida Xizmat uchun to'lagan summangizdan oshmasligi kerak.",
      },
      {
        heading: "10. Bekor qilish",
        body: "Hisobingizni istalgan vaqtda o'chirishingiz mumkin. Agar siz ushbu Shartlarni buzsangiz yoki Xizmatga zarar yetkazuvchi faoliyat bilan shug'ullansangiz, kirishingizni to'xtatib qo'yishimiz mumkin. Bekor qilingandan so'ng, qonun talab qilmasa, ma'lumotlaringiz 30 kun ichida o'chiriladi.",
      },
      {
        heading: "11. Intellektual mulk",
        body: "Xizmat, shu jumladan uning dizayni, kodi, brendingi va hujjatlari BotForge AI intellektual mulki hisoblanadi. Ushbu Shartlar sizga bizning savdo belgilarimiz, logotiplarimiz yoki boshqa mulkiy materiallarimizga hech qanday huquq bermaydi.",
      },
      {
        heading: "12. Amaldagi qonun",
        body: "Ushbu Shartlar xalqaro tijorat qonunchiligiga muvofiq boshqariladi va sharhlashadi. Har qanday nizolar avval yaxshi niyatdagi muzokaralar, keyin zarur bo'lsa majburiy arbitraj orqali hal qilinadi.",
      },
      {
        heading: "13. Aloqa",
        body: "Ushbu Shartlar bo'yicha savollar uchun support@botforge.ai manziliga murojaat qiling.",
      },
    ],
  },
  ru: {
    title: "Условия использования",
    lastUpdated: "Последнее обновление: 31 мая 2026 г.",
    sections: [
      {
        heading: "1. Принятие условий",
        body: "Используя платформу BotForge AI («Сервис»), вы соглашаетесь с настоящими Условиями использования («Условия»). Если вы не согласны с этими Условиями, не используйте Сервис. Мы можем обновлять Условия в любое время; продолжение использования после изменений означает принятие.",
      },
      {
        heading: "2. Описание сервиса",
        body: "BotForge AI — облачная платформа для создания, настройки и развёртывания чат-ботов на базе ИИ для генерации лидов и общения с клиентами через виджет на сайте и Telegram. Сервис включает создание ботов, управление базой знаний, аналитику и интеграцию каналов.",
      },
      {
        heading: "3. Регистрация аккаунта",
        body: "При регистрации необходимо предоставить точную и полную информацию. Вы несёте ответственность за безопасность учётных данных и за всю активность в аккаунте. Для использования Сервиса вам должно быть не менее 18 лет или возраста совершеннолетия в вашей юрисдикции.",
      },
      {
        heading: "4. Допустимое использование",
        body: "Вы обязуетесь не: (а) использовать Сервис в незаконных целях; (б) распространять спам, вредоносное ПО или вредоносный контент через ботов; (в) выдавать себя за другое лицо; (г) пытаться получить несанкционированный доступ к Сервису; (д) собирать персональные данные без надлежащего согласия; (е) перепродавать Сервис без письменного разрешения.",
      },
      {
        heading: "5. Ваш контент и данные",
        body: "Вы сохраняете право собственности на весь контент, загруженный в Сервис (документы, файлы базы знаний, конфигурации ботов). Загружая контент, вы предоставляете BotForge AI ограниченную лицензию на обработку, хранение и предоставление контента исключительно для работы Сервиса.",
      },
      {
        heading: "6. Ответы, генерируемые ИИ",
        body: "Ответы чат-бота генерируются моделями искусственного интеллекта и не всегда могут быть точными, полными или уместными. BotForge AI не гарантирует точность сгенерированного контента. Вы несёте ответственность за настройку поведения бота, базы знаний и тона. BotForge AI не несёт ответственности за решения, принятые на основе ответов ИИ.",
      },
      {
        heading: "7. Тарифы и оплата",
        body: "Доступны бесплатные планы с ограничениями. Платные планы оплачиваются ежемесячно через Stripe. Все платежи не подлежат возврату, за исключением случаев, предусмотренных законом. Мы оставляем за собой право изменить цены с уведомлением за 30 дней. При неудачной оплате аккаунт может быть переведён на бесплатный тариф.",
      },
      {
        heading: "8. Доступность сервиса",
        body: "Мы стремимся к высокой доступности, но не гарантируем бесперебойный доступ. Сервис может быть временно недоступен из-за обслуживания, обновлений или обстоятельств непреодолимой силы. Мы приложим усилия для уведомления о плановых работах.",
      },
      {
        heading: "9. Ограничение ответственности",
        body: "В максимальной степени, допускаемой законом, BotForge AI не несёт ответственности за косвенные, случайные, специальные или штрафные убытки, а также за потерю прибыли, данных или деловых возможностей. Наша общая ответственность не превышает сумму, уплаченную за Сервис за 12 месяцев, предшествующих претензии.",
      },
      {
        heading: "10. Прекращение",
        body: "Вы можете удалить аккаунт в любое время. Мы можем приостановить или прекратить доступ при нарушении Условий. После прекращения данные будут удалены в течение 30 дней, если иное не требуется законом.",
      },
      {
        heading: "11. Интеллектуальная собственность",
        body: "Сервис, включая дизайн, код, брендинг и документацию, является интеллектуальной собственностью BotForge AI. Настоящие Условия не предоставляют вам прав на наши товарные знаки, логотипы или иные материалы.",
      },
      {
        heading: "12. Применимое право",
        body: "Настоящие Условия регулируются международным коммерческим правом. Споры разрешаются путём добросовестных переговоров, а при необходимости — обязательного арбитража.",
      },
      {
        heading: "13. Контакты",
        body: "По вопросам об Условиях обращайтесь по адресу support@botforge.ai.",
      },
    ],
  },
};

export default function TermsPage() {
  const { lang } = useLanguage();
  const c = content[lang];

  return (
    <main className="bf-main--narrow" style={{ paddingBottom: "3rem" }}>
      <h1 style={{ marginTop: 0 }}>{c.title}</h1>
      <p style={{ color: "var(--bf-text-muted)", marginBottom: "2rem", fontSize: "0.875rem" }}>
        {c.lastUpdated}
      </p>
      {c.sections.map((s, i) => (
        <section key={i} style={{ marginBottom: "1.75rem" }}>
          <h2 style={{ fontSize: "1.125rem", marginBottom: "0.5rem" }}>{s.heading}</h2>
          <p style={{ color: "var(--bf-text-muted)", lineHeight: 1.7, margin: 0 }}>{s.body}</p>
        </section>
      ))}
    </main>
  );
}
